[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "hyperfython"
author = "Leonardo Barreiros"
author-email = "leossb36@gmail.com"
home-page = "https://github.com/leossb36"
classifiers = ["License :: OSI Approved :: MIT License"]

