from lark import Lark, InlineTransformer

grammar = Lark(r"""

?start : expr

?expr  : list

?list  : "f" "(" ( (name "," tag|tag|name) ("," atribute)* ("," func)? ) ")" -> lista

?atribute :  ( "$" name ":" name )  -> atributo

?func  : "{" list+ "}" -> funcao

?tag   :  "*" name  -> tag

?name  : STRING -> nome
      
// Terminais
SYMBOL  : /[-!$%^&*()_+|~=`{}\[\]:";'<>?,.\/ ]/
STRING    : /[a-zA-Z0-9 ]+/

%ignore /\s+/
%ignore /;[^\n]*/
""")