?start : "fython" block

?block : "[" expr "]" -> block

?expr  : dict* -> expr

?dict  : "{" (atom ":" dict)* "}" -> dict
       | "{" "content" ":" block "}"
       | "{" "style" ":" block "}"
       | "{" "text" ":" block "}"
       | "{" pair ("," pair)* "}"

?pair : atom ":" atom -> pair
      | atom*

?atom : CHAR -> name
      | SYMBOL -> symbol

// Terminais
SYMBOL  : /[-!$%^&*()_+|~=`{}\[\]:";'<>?,.\/ ]/
CHAR    : /[a-zA-Z0-9]\w*/

%ignore /\s+/
%ignore /;[^\n]*/