HTMLTAGS = ['p', 'pre','section','div', 'head','title',
            'html','article','aside','details','span',
            'small','footer', 'header','main', 'figure',
            'figcaption', 'h1', 'h2', 'iframe','style',
            'button','fieldset', 'label', 'legend',
            'h3', 'h4', 'h5', 'h6', 'span', 'applet',
            'big', 'center', 'dir',
            'head', 'footer', 'body', 'body','progress',
            'samp','summary','time','var',
            'abbr', 'blockquote', 'code', 
            'b', 'em', 'del', 'i', 'ins', 'mark',
            'p', 'sub', 'sup', 'u', 'textarea', 'canvas',
            'img', 'a', 'bdo', 'address', 'dialog',
            'cite', 'datalist', 'kbd', 'meter', 'progress',]

CLOSEDHTMLTAGS = ['img', 'input', 'br', 'hr',
                  'wbr','meta','link', 'embed','basefont']

ATRIBUTO = [ 'accept', 'accept-charset', 'accesskey',
             'action', 'align', 'alt', 'async',
             'autocomplete', 'autofocus', 'autoplay',
             'bgcolor', 'border', 'buffered', 'challenge',
             'charset', 'checked', 'cite', 'class', 'code',
             'codebase', 'color', 'cols', 'colspan', 'content',
             'contenteditable', 'contextmenu', 'controls',
             'coords', 'data', 'datetime', 'default', 'defer',
             'dir', 'dirname', 'disabled', 'draggable', 'dropzone',
             'enctype', 'for', 'form', 'headers', 'height', 'hidden',
             'high', 'href', 'hreflang', 'http-equiv', 'icon', 'id', 
             'ismap', 'itemprop', 'keytype', 'kind', 'label', 'lang',
             'language', 'list', 'loop', 'low', 'manifest', 'max',
             'maxlength', 'media', 'method', 'min', 'multiple', 'name',
             'novalidate', 'open', 'optimum', 'pattern', 'ping',
             'placeholder', 'poster', 'preload', 'pubdate', 'radiogroup',
             'readonly', 'rel', 'required', 'reversed', 'rows', 'rowspan',
             'sandbox', 'spellcheck', 'scope', 'scoped', 'seamless',
             'selected', 'shape', 'size', 'sizes', 'span', 'src', 'srcdoc',
             'srclang', 'start', 'step', 'style', 'summary', 'target',
             'title', 'type', 'usemap', 'value', 'width', 'wrap']
